### ISSUE TITLE
Known upstream issues

### ISSUE THREAD

**Issue by putianyi889** [eee555/saolei_website#50]
- #45 
- https://github.com/element-plus/element-plus/issues/15868
  Workaround:
  - disable ellipsis #49 
  - improve screen-width compatibility #51 
- https://github.com/element-plus/element-plus/issues/14035
  This issue dominates table rendering. Workaround:
  - use `v-if` to optionally render poppers in tables #51

**Comment by eee555** [comment]
那我们这边降一下级

**Comment by putianyi889** [comment]
倒也不用，降级会少功能。第二个我已经应付过去了，第三个已解决。这个issue是提示当上游解决了那些问题以后我们就可以把workaround去掉了
